---
title: "Caret Package Assessment"
author: "Silpa Velagapudi"
date: "October 12, 2019"
output: html_document
---

```{r}
library(tidyverse)
library(rpart)
library(caret)
data("tissue_gene_expression")
set.seed(1991) #set.seed(1, sample.kind = "Rounding") if using R 3.6 or later
#y <- tissue_gene_expression$y
#x <- tissue_gene_expression$x
#x <- x[, sample(ncol(x), 10)]

#train_knn_cv <- train(x,y, method = "rpart", 
#                      data = tissue_gene_expression,
#                      tuneGrid = data.frame(cp =seq(0, 0.1, 0.01)),
#                      trControl = control)
#ggplot(train_knn_cv, highlight = TRUE)

#tissue_gene_expression$x
#tissue_gene_expression$y
y <- droplevels(tissue_gene_expression$y)
    x <- tissue_gene_expression$x
full_genes <- data.frame(y = y,
                   x = x)
train_rpart <- with(full_genes, train(y~., method = "rpart",
                     tuneGrid = data.frame(cp=seq(0, 0.1, 0.01)),
                     data = full_genes, control = rpart.control(minsplit = 0)))
ggplot(train_rpart,highlight=TRUE)

```

```{r}
#summary(train_rpart)
```

```{r}

fit <- with(full_genes, train(y~., method = "rf",
                     tuneGrid = data.frame(mtry=seq(50, 200, 25)),
                     data = full_genes,nodesize=1))
ggplot(fit,highlight=TRUE)
```

```{r}
#fit
tree_terms <- as.character(unique(train_rpart$finalModel$frame$var[!(train_rpart$finalModel$frame$var == "<leaf>")]))
tree_terms
```

```{r}
imp <- varImp(fit,scale=FALSE)
imp
```

```{r}
#summary(fit)
imp <- varImp(train_rpart)#,scale=FALSE)
imp
imp$importance %>% mutate(name = row.names(.), rank = rank(.$Overall), rank_t=rank(name)) %>% filter(name == "x.CFHR4")
imp$importance
```


