---
title: "liner models assessment"
author: "Silpa Velagapudi"
date: "September 2, 2019"
output: html_document
---
```{r}
library(tidyverse)
library(broom)
library(Lahman)
Teams_small <- Teams %>% 
    filter(yearID %in% 1961:2001) %>% 
    mutate(avg_attendance = attendance/G)
```

```{r}
fit <- Teams %>% 
  filter(yearID %in% 1961:2001) %>% 
  mutate(BB = BB/G, HR = HR/G,  R = R/G,avg_attendance = attendance/G) 
a <- fit %>% lm(R ~ avg_attendance, data = .)
tidy(a, conf.int=TRUE )
  
b <- fit %>% lm(HR ~ avg_attendance, data = .)
tidy(b, conf.int=TRUE )

```

```{r}
fit <- Teams %>% 
  filter(yearID %in% 1961:2018) %>% group_by(yearID) %>%
  mutate(BB = BB/G, HR = HR/G,  R = R/G) %>%
  select(yearID,BB,HR,R)
fit %>% ggplot(aes(yearID, BB, color = yearID)) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm")

```

```{r}
res <- Teams %>%
    filter(yearID %in% 1961:2018) %>%
    #group_by(yearID) %>%
    do(tidy(lm(R ~ BB + HR, data = .))) %>%
    ungroup() %>% filter(term=="BB")
res
tidy(lm(yearID~estimate,data=res),conf.int=TRUE)
res %>%
    filter(term == "BB") %>%
    ggplot(aes(yearID, estimate)) +
    geom_point() +
    geom_smooth(method = "lm")
```

