---
title: "Movielens Project"
author: "Silpa Velagapudi"
date: "November 28, 2019"
output: html_document
---
```{r}
################################
# Create edx set, validation set
################################

# Note: this process could take a couple of minutes

if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if(!require(caret)) install.packages("caret", repos = "http://cran.us.r-project.org")
if(!require(data.table)) install.packages("data.table", repos = "http://cran.us.r-project.org")

# MovieLens 10M dataset:
# https://grouplens.org/datasets/movielens/10m/
# http://files.grouplens.org/datasets/movielens/ml-10m.zip

dl <- tempfile()
download.file("http://files.grouplens.org/datasets/movielens/ml-10m.zip", dl)

ratings <- fread(text = gsub("::", "\t", readLines(unzip(dl, "ml-10M100K/ratings.dat"))),
                 col.names = c("userId", "movieId", "rating", "timestamp"))

movies <- str_split_fixed(readLines(unzip(dl, "ml-10M100K/movies.dat")), "\\::", 3)
colnames(movies) <- c("movieId", "title", "genres")

```

```{r}
movies <- as.data.frame(movies) %>% mutate(movieId = as.numeric(levels(movieId))[movieId],
                                           title = as.character(title),
                                           genres = as.character(genres))

movielens <- left_join(ratings, movies, by = "movieId")
#nrow(movielens)

# Validation set will be 10% of MovieLens data

set.seed(1)#, sample.kind="Rounding")
# if using R 3.5 or earlier, use `set.seed(1)` instead
test_index <- createDataPartition(y = movielens$rating, times = 1, p = 0.1, list = FALSE)
edx <- movielens[-test_index,]
temp <- movielens[test_index,]

# Make sure userId and movieId in validation set are also in edx set

validation <- temp %>% 
     semi_join(edx, by = "movieId") %>%
     semi_join(edx, by = "userId")

# Add rows removed from validation set back into edx set

removed <- anti_join(temp, validation)
edx <- rbind(edx, removed)

rm(dl, ratings, movies, test_index, temp, movielens, removed)
```
Number of rows and columns of edx
```{r}
#to find number of rows
nrow(edx)
nrow(validation)
#to find number of columns
ncol(edx)
```
Number of zero ratings:
```{r}
zero_rating <- edx %>% filter(rating==0)
nrow(zero_rating)
```
Number of 3 rating:
```{r}
three_rating <- edx %>% filter(rating==3)
nrow(three_rating)

```
Number of different movies:
```{r}
a <- edx %>% group_by(movieId) %>% summarize(a=n())
nrow(a)
```
number of distinct users:
```{r}

a <- edx %>% group_by(userId) %>% summarize(a=n())
nrow(a)

```
movie ratings based on genres 
```{r}
#Ratings for genres Drama
edx %>% filter(genres %like% "Drama") %>% summarize(a=n())
#Ratings for genres Comedy
edx %>% filter(genres %like% "Comedy") %>% summarize(a=n())
#Ratings for genres Thriller
edx %>% filter(genres %like% "Thriller") %>% summarize(a=n())
#Ratings for genres Romance
edx %>% filter(genres %like% "Romance") %>% summarize(a=n())

```
Movie with greatest ratings
```{r}
#edx %>%group_by(title) %>% filter(title %like% c("Speed 2: Cruise Control"))
#great movie ratings
edx %>%group_by(title) %>% filter(title %in% c("Forrest Gump (1994)","Jurassic Park (1993)","Pulp Fiction (1994)","Shawshank Redemption, The (1994)","Speed 2: Cruise Control (1997)")) %>% summarize(a=n()) %>% arrange(desc(a))

```
Movie based on rating
```{r}
edx %>%group_by(rating) %>% summarize(a=n()) %>% arrange(desc(a))


```

