---
title: "smoothing Assessment"
author: "Silpa Velagapudi"
date: "September 11, 2019"
output: html_document
---
```{r}
library(tidyverse)
library(lubridate)
library(purrr)
library(pdftools)
library(caret)
    
fn <- system.file("extdata", "RD-Mortality-Report_2015-18-180531.pdf", package="dslabs")
dat <- map_df(str_split(pdf_text(fn), "\n"), function(s){
	s <- str_trim(s)
	header_index <- str_which(s, "2015")[1]
	tmp <- str_split(s[header_index], "\\s+", simplify = TRUE)
	month <- tmp[1]
	header <- tmp[-1]
	tail_index  <- str_which(s, "Total")
	n <- str_count(s, "\\d+")
	out <- c(1:header_index, which(n==1), which(n>=28), tail_index:length(s))
	s[-out] %>%
		str_remove_all("[^\\d\\s]") %>%
		str_trim() %>%
		str_split_fixed("\\s+", n = 6) %>%
		.[,1:5] %>%
		as_data_frame() %>% 
		setNames(c("day", header)) %>%
		mutate(month = month,
			day = as.numeric(day)) %>%
		gather(year, deaths, -c(day, month)) %>%
		mutate(deaths = as.numeric(deaths))
}) %>%
	mutate(month = recode(month, "JAN" = 1, "FEB" = 2, "MAR" = 3, "APR" = 4, "MAY" = 5, "JUN" = 6, 
                          "JUL" = 7, "AGO" = 8, "SEP" = 9, "OCT" = 10, "NOV" = 11, "DEC" = 12)) %>%
	mutate(date = make_date(year, month, day)) %>%
      filter(date <= "2018-05-01")
```



```{r}
dat %>% ggplot(aes(date,deaths)) + geom_point() + geom_smooth(color="red",span=60/1205,method.args=list(degree=1))
dat$date.numeric = as.numeric(dat$date)/(24*60*60)
span <- 60
```

```{r}
dat <- dat %>% filter(!is.na(deaths))
x <- dat$date
y <- dat$deaths
#x

#fit
#fit$fitted


dat %>%
  mutate(loess = predict(loess(y ~ as.numeric(x), data = dat, span = 1/18))) %>%
  ggplot(aes(x, y)) +
  geom_point(color = "black", size = 3) +
  geom_line(aes(y = loess), col = "red", lwd =2) +  geom_smooth(degree=1)

dat %>% mutate(smooth=fit$fitted) %>% ggplot(aes(date,deaths)) + geom_point(size=3,alpha=0.5,color="grey")+geom_line(aes(date,deaths),color="red",lwd=1)
```




```{r}
datn <- dat %>% filter(!is.na(deaths))
dates <- datn$date
deaths <- datn$deaths

fit <-loess(as.numeric(dates) ~ deaths)
fit
#predict(fit)
dat %>%
  mutate(loess = predict(loess(deaths ~ as.numeric(dates), data = dat, span = 1/18))) %>%
  ggplot(aes(dates, deaths)) +
  geom_point(color = "black", size = 3) +
  geom_line(aes(deaths = loess), col = "red", lwd =2)

dat %>% 
	mutate(smooth = predict(fit), day = yday(dates), year = as.character(year(dates))) %>%
	ggplot(aes(day, smooth, col = year)) +
	geom_line(lwd = 2)
#as.numeric(x)

dat %>% 
	mutate(smooth = predict(fit, as.numeric(dates)), day = mday(dates), year = as.character(year(dates))) %>%
	ggplot(aes(day, smooth, col = year)) +
	geom_line(lwd = 2)

dat %>% 
	mutate(smooth = predict(fit, as.numeric(dates)), day = yday(dates), year = as.character(year(dates))) %>%
	ggplot(aes(day, smooth)) +
  	geom_line(lwd = 2)


dat %>% 
	mutate(smooth = predict(fit, as.numeric(dates)), day = yday(dates), year = as.character(year(dates))) %>%
	ggplot(aes(day, smooth, col = year)) +
	geom_line(lwd = 2)
```


